domain: gamma-software.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://gamma-software.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /gamma-software.github.io/  
plugin: jekyll-include-cache